-- Migration: Add user table for registration and sign-in
-- Run: PGPASSWORD=dev123 psql -d davidlong_tech -U dev_user -h localhost -f migrations/001_add_user_table.sql

CREATE TABLE IF NOT EXISTS tbl_user (
  user_id       INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         VARCHAR(255) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  display_name  VARCHAR(255) NULL,
  created_at    TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT tbl_user_email_uniq UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS idx_tbl_user_email ON tbl_user(email);

COMMENT ON TABLE tbl_user IS 'Registered users; password_hash is bcrypt.';
